[phases.setup]
nixPkgs = ["python3"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "pip install -r ios_mcp_server/requirements.txt"]

[start]
cmd = "echo '--- Listing files in container ---' && ls -R . && echo '--- Starting server ---' && gunicorn ios_mcp_server.fastmcp_server:app -w 1 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --log-level debug --timeout 120" 