[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "pip install -r requirements.txt", "pip install -e ."]

[start]
cmd = "python fastmcp_server.py" 