[phases.setup]
nixPkgs = ["python3"]

[phases.install]
cmds = [
    "mkdir -p /app",
    "cp -r . /app/",
    "cd /app",
    "python -m pip install --upgrade pip",
    "pip install -r requirements.txt"
]
workdir = "/app"

[start]
cmd = "cd /app && gunicorn fastmcp_server:app -w 1 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --log-level debug --timeout 120"
workdir = "/app" 